### ISSUE TITLE
Multiple errors/warnings in test

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/yari#10335]
Following commands logs a few warnings and errors:
```bash
yarn test:kumascript
cross-env NODE_ENV=production NODE_OPTIONS='--no-warnings=ExperimentalWarning --loader ts-node/esm' node 
```

```
In ListGroups the smartLink to /en-US/docs/Web/API/Background_Fetch_API is broken! (does not exist)

and

The livesampleurl macro on /en-US/docs/Web/Fubar failed to render. Error: /home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs:1
 >> 1| <%
    2| // Returns the URL used to access as a live sample the code
    3| // at a given ID.
    4| //The livesampleurl macro on /en-US/docs/Web/Fubar failed to render. Error: /home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs:1
 >> 1| <%
    2| // Returns the URL used to access as a live sample the code
    3| // at a given ID.
    4| //

/home/runner/work/yari/yari/client/build/en-us/docs/web/fubar
/en-us/docs/web/fubar references /en-us/docs/does/not/exist, which does not exist
    at Object.ensureExistence (file:///home/runner/work/yari/yari/kumascript/src/api/wiki.ts:[103](https://github.com/OnkarRuikar/yari/actions/runs/7554550415/job/20567617877#step:7:104):13)
    at eval ("/home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs":32:6)
    at LiveSampleURL (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:703:17)
    at /home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:260:40
    at new Promise (<anonymous>)
    at tryHandleCache (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:258:14)
    at Object.renderFile (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:491:10)
    at Templates.render (file:///home/runner/work/yari/yari/kumascript/src/templates.ts:[105](https://github.com/OnkarRuikar/yari/actions/runs/7554550415/job/20567617877#step:7:106):34)
    at Environment._renderTemplate (file:///home/runner/work/yari/yari/kumascript/src/environment.ts:[175](https://github.com/OnkarRuikar/yari/actions/runs/7554550415/job/20567617877#step:7:176):33)
    at eval ("/home/runner/work/yari/yari/kumascript/macros/EmbedLiveSample.ejs":82:17) {
  path: '/home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs'
}


/home/runner/work/yari/yari/client/build/en-us/docs/web/fubar
/en-us/docs/web/fubar references /en-us/docs/does/not/exist, which does not exist
    at Object.ensureExistence (file:///home/runner/work/yari/yari/kumascript/src/api/wiki.ts:[103](https://github.com/OnkarRuikar/yari/actions/runs/7554550415/job/20567617877#step:7:104):13)
    at eval ("/home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs":32:6)
    at LiveSampleURL (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:703:17)
    at /home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:260:40
    at new Promise (<anonymous>)
    at tryHandleCache (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:258:14)
    at Object.renderFile (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:491:10)
    at Templates.render (file:///home/runner/work/yari/yari/kumascript/src/templates.ts:[105](https://github.com/OnkarRuikar/yari/actions/runs/7554550415/job/20567617877#step:7:106):34)
    at Environment._renderTemplate (file:///home/runner/work/yari/yari/kumascript/src/environment.ts:[175](https://github.com/OnkarRuikar/yari/actions/runs/7554550415/job/20567617877#step:7:176):33)
    at eval ("/home/runner/work/yari/yari/kumascript/macros/EmbedLiveSample.ejs":82:17) {
  path: '/home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs'
}
```

<details open>
  <summary>Complete Logs</summary>
```log
$ cross-env NODE_ENV=production NODE_OPTIONS='--no-warnings=ExperimentalWarning --loader ts-node/esm' node build/cli.ts
CONTENT_ROOT:            /home/runner/work/yari/yari/testing/content/files
CONTENT_TRANSLATED_ROOT: /home/runner/work/yari/yari/testing/translated-content/files
/home/runner/work/yari/yari/client/build/fr/docs/web/embeddable
/home/runner/work/yari/yari/client/build/fr/docs/web/foo
/home/runner/work/yari/yari/client/build/fr/docs/web/spec_section_extraction
/home/runner/work/yari/yari/client/build/zh-cn/docs/web/foo
/home/runner/work/yari/yari/client/build/zh-tw/docs/web/foo
/home/runner/work/yari/yari/client/build/en-us/docs/markdown
/home/runner/work/yari/yari/client/build/en-us/docs/web
/home/runner/work/yari/yari/client/build/en-us/docs/glossary/bézier_curve
/home/runner/work/yari/yari/client/build/en-us/docs/learn/some_code
In ListGroups the smartLink to /en-US/docs/Web/API/Background_Fetch_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Background_Tasks_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Barcode_Detection_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Battery_Status_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Beacon_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_Bluetooth_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Broadcast_Channel_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/CSS_Counter_Styles is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/CSS_Font_Loading_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/CSS_Painting_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/CSS_Typed_OM_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/CSS_Object_Model is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Canvas_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Channel_Messaging_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Clipboard_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Console_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Contact_Picker_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Content_Index_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Credential_Management_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Document_Object_Model is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Encoding_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Encrypted_Media_Extensions_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Fetch_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/File_and_Directory_Entries_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/File_System_Access_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Frame_Timing_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Fullscreen_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Gamepad_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Geolocation_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/HTML_Drag_and_Drop_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/HTML_Sanitizer_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Performance_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/History_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/MediaStream_Image_Capture_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/IndexedDB_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Intersection_Observer_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Long_Tasks_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Media_Capabilities_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Media_Streams_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Media_Session_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Media_Source_Extensions_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/MediaStream_Recording_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Navigation_timing_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Network_Information_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Payment_Request_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Performance_Timeline is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_Periodic_Background_Synchronization_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Permissions_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Picture-in-Picture_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Pointer_events is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Pointer_Lock_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Presentation_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Proximity_Events is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Push_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Resize_Observer_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Resource_Timing_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Screen_Capture_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Screen_Wake_Lock_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Sensor_APIs is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Server-sent_events is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Service_Worker_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Storage_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Storage_Access_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Streams_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Touch_events is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/URL_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Vibration_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Visual_Viewport_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_Animations_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_Audio_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_Authentication_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_Crypto_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_MIDI_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Notifications_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_Speech_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_Storage_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Web_Workers_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/WebGL_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/WebHID_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/WebRTC_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/WebVR_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/WebVTT_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/WebXR_Device_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/Websockets_API is broken! (does not exist)
In ListGroups the smartLink to /en-US/docs/Web/API/XMLHttpRequest is broken! (does not exist)
/home/runner/work/yari/yari/client/build/en-us/docs/web/api
/home/runner/work/yari/yari/client/build/en-us/docs/web/bar
/home/runner/work/yari/yari/client/build/en-us/docs/web/badbcdqueries
/home/runner/work/yari/yari/client/build/en-us/docs/web/bcd_table_extraction
Unable to decodeURI 'https://www.ecma-international.org/ecma-262/6.0/#sec-get-%typedarray%.prototype.buffer'. Will proceed without.
/home/runner/work/yari/yari/client/build/en-us/docs/web/brokenlinks
/home/runner/work/yari/yari/client/build/en-us/docs/web/brokenlinks_repeats
/home/runner/work/yari/yari/client/build/en-us/docs/web/brokenlinks_markdown
/home/runner/work/yari/yari/client/build/en-us/docs/web/check_notecards
/home/runner/work/yari/yari/client/build/en-us/docs/web/donttranslatethese
/home/runner/work/yari/yari/client/build/en-us/docs/web/duplicate_ids
Building live sample from another page: foo in /home/runner/work/yari/yari/testing/content/files/en-us/web/embeddable/index.html
/home/runner/work/yari/yari/client/build/en-us/docs/web/embeddable
In /en-US/docs/Web/Empty_image there's an img tag without src (<img src="" data-flaw="image1">)
/home/runner/work/yari/yari/client/build/en-us/docs/web/empty_image
/home/runner/work/yari/yari/client/build/en-us/docs/web/externallinks
/home/runner/work/yari/yari/client/build/en-us/docs/web/fixable_flaws
The livesampleurl macro on /en-US/docs/Web/Fubar failed to render. Error: /home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs:1
 >> 1| <%
    2| // Returns the URL used to access as a live sample the code
    3| // at a given ID.
    4| //

/home/runner/work/yari/yari/client/build/en-us/docs/web/fubar
/en-us/docs/web/fubar references /en-us/docs/does/not/exist, which does not exist
    at Object.ensureExistence (file:///home/runner/work/yari/yari/kumascript/src/api/wiki.ts:[103](https://github.com/OnkarRuikar/yari/actions/runs/7554550415/job/20567617877#step:7:104):13)
    at eval ("/home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs":32:6)
    at LiveSampleURL (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:703:17)
    at /home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:260:40
    at new Promise (<anonymous>)
    at tryHandleCache (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:258:14)
    at Object.renderFile (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:491:10)
    at Templates.render (file:///home/runner/work/yari/yari/kumascript/src/templates.ts:[105](https://github.com/OnkarRuikar/yari/actions/runs/7554550415/job/20567617877#step:7:106):34)
    at Environment._renderTemplate (file:///home/runner/work/yari/yari/kumascript/src/environment.ts:[175](https://github.com/OnkarRuikar/yari/actions/runs/7554550415/job/20567617877#step:7:176):33)
    at eval ("/home/runner/work/yari/yari/kumascript/macros/EmbedLiveSample.ejs":82:17) {
  path: '/home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs'
}
The embedlivesample macro on /en-US/docs/Web/Fubar failed to render. Error: /home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs:1
 >> 1| <%
    2| // Returns the URL used to access as a live sample the code
    3| // at a given ID.
    4| //

/en-us/docs/web/fubar references /en-us/docs/does/not/exist, which does not exist
    at Object.ensureExistence (file:///home/runner/work/yari/yari/kumascript/src/api/wiki.ts:103:13)
    at eval ("/home/runner/work/yari/yari/kumascript/macros/LiveSampleURL.ejs":32:6)
    at LiveSampleURL (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:703:17)
    at /home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:260:40
    at new Promise (<anonymous>)
    at tryHandleCache (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:258:14)
    at Object.renderFile (/home/runner/work/yari/yari/node_modules/ejs/lib/ejs.js:491:10)
    at Templates.render (file:///home/runner/work/yari/yari/kumascript/src/templates.ts:105:34)
    at Environment._renderTemplate (file:///home/runner/work/yari/yari/kumascript/src/environment.ts:175:33)
    at eval ("/home/runner/work/yari/yari/kumascript/macros/EmbedLiveSample.ejs":82:17) {
  path: '/home/runner/work/yari/yari/kumascript/macros/EmbedLiveSample.ejs'
}
/home/runner/work/yari/yari/client/build/en-us/docs/web/heading_links
The listsubpagesforsidebar macro on /en-US/docs/Web/Foo failed to render. TypeError: /home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs:1
 >> 1| <%
    2| // Inserts a tree of subpages of the specified page to be used in the sidebar (quicklinks)
    3| // Displays common flags/icons
    4| // Includes the parent page at the top of the list.

pages is not iterable
    at eval ("/home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs":50:20) {
  path: '/home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs'
}
The htmlsidebar macro on /en-US/docs/Web/Foo failed to render. TypeError: /home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs:1
 >> 1| <%
    2| // Inserts a tree of subpages of the specified page to be used in the sidebar (quicklinks)
    3| // Displays common flags/icons
    4| // Includes the parent page at the top of the list.

pages is not iterable
    at eval ("/home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs":50:20) {
  path: '/home/runner/work/yari/yari/kumascript/macros/HTMLSidebar.ejs'
}
/home/runner/work/yari/yari/client/build/en-us/docs/web/foo
/home/runner/work/yari/yari/client/build/en-us/docs/web/homepage_links
/home/runner/work/yari/yari/client/build/en-us/docs/web/html_headings
The listsubpagesforsidebar macro on /en-US/docs/Web/InteractiveExample failed to render. TypeError: /home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs:1
 >> 1| <%
    2| // Inserts a tree of subpages of the specified page to be used in the sidebar (quicklinks)
    3| // Displays common flags/icons
    4| // Includes the parent page at the top of the list.

pages is not iterable
    at eval ("/home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs":50:20) {
  path: '/home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs'
}
The htmlsidebar macro on /en-US/docs/Web/InteractiveExample failed to render. TypeError: /home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs:1
 >> 1| <%
    2| // Inserts a tree of subpages of the specified page to be used in the sidebar (quicklinks)
    3| // Displays common flags/icons
    4| // Includes the parent page at the top of the list.

pages is not iterable
    at eval ("/home/runner/work/yari/yari/kumascript/macros/ListSubpagesForSidebar.ejs":50:20) {
  path: '/home/runner/work/yari/yari/kumascript/macros/HTMLSidebar.ejs'
}
```
</details>

**Comment by caugner** [comment]
Closing, as we're archiving Yari, so we won't fix these tests.
