### ISSUE TITLE
<pre> tags full of HTML is a flaw

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1404]
See https://gist.github.com/peterbe/291c10e81976433f15aac6b2fad864fe

There are 225 pages in the active English content where the `<pre>` tags's *content* is the fully Prism rendered HTML soup. Look at [this page](https://github.com/mdn/content/blob/2fe17ae53f21de7e4289bfdf03efb89438e1e90c/files/en-us/games/techniques/crisp_pixel_art_look/index.html#L65) for example:

```html
<pre class="brush: css"><code class="language-css"><span class="selector token">canvas </span><span class="punctuation token">{</span>
  </code>width: 512px;
  height: 512px;<code class="language-css">
  <span class="property token">image-rendering</span><span class="punctuation token">:</span> -moz-crisp-edges<span class="punctuation token">;</span>
  <span class="property token">image-rendering</span><span class="punctuation token">:</span> -webkit-crisp-edges<span class="punctuation token">;</span>
  <span class="property token">image-rendering</span><span class="punctuation token">:</span> pixelated<span class="punctuation token">;
  image-rendering: crisp-edges;</span>
<span class="punctuation token">}</span>
</code></pre>
```

I looks like somebody copy and pasted, into the Source mode I presumed (of the WYSIWYG editor), the HTML that gets produced in the DOM by Prism when executed in the browser. 

What it should be is:

```html
<pre class="brush: css">&lt;canvas id="game" width="128" height="128"&gt;&lt/canvas&gt;</pre>
```

If we one day convert this (source) page from HTML to Markdown, we'll want it to say:

```markdown

``html
<canvas id="game" width="128" height="128"></canvas>
``

```
(I'm using double-backticks instead of triple because filing this issue with code is also already in Markdown)
That, as a content writer, is the ideal form to enter your code examples.

**Comment by peterbe** [comment]
The more I think about it, the more I think it should just be a one-off fix in the importer. We already have `cheerio` objects there for every blob of HTML. It'll take care of the 225 pages all in one sweep. Having to create another flaw and infra for making it fixable etc. isn't terribly hard but not completely free either. And how likely is it that people will keep pasting these in now that a PR reviewer can be there to spot it?

**Comment by peterbe** [comment]
We somehow failed to notice this. Or perhaps the content of `mdn/content` has changed under our noses. 
But if you run:
```
▶ BUILD_FOLDERSEARCH=learn yarn build
...
Injecting flaws into /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/learn/forms/how_to_build_custom_form_controls/example_3/index.html (/en-US/docs/Learn/Forms/How_to_build_custom_form_controls/Example_3) failed.
error while building documents: TypeError: Cannot read property 'replace' of null
    at addFlaw (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:250:30)
    at Node.<anonymous> (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:288:5)
    at initialize.exports.each (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/cheerio/lib/api/traversing.js:300:24)
    at injectPreWithHTMLFlaws (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:286:33)
    at injectFlaws (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:27:3)
    at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:246:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async buildDocuments (/Users/peterbe/dev/MOZILLA/MDN/yari/build/cli.js:65:59)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
