### ISSUE TITLE
A lot of Document.read on folders that will never work

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1458]
I put in `fs.appendFileSync("/tmp/read.log", `${folder}\t${filePath}\n`, "utf-8");` inside the `Document.read` function. 
Then, I built it all `yarn build` (no filtering). 

What I noticed was that in 23.6% of the times, that the `folder` argument looks something like this: 
```
en-us/docs/web/api/vrdisplay/capabilities
```
There is no folder in `$CONTENT_ROOT` called `./en-us/docs/web/api/vrdisplay/capabilities/index.html`. Maybe, it would have worked if it was `./en-us/web/api/vrdisplay/capabilities/index.html` which has a larger chance of working. 

There are also a bunch that aren't `en-us` which is probably causing problems. For example:
```
web/resource_timing_api/using_the_resource_timing_api
en/xml-stylesheet
docs/api/webrtc_api/session_lifetime
zh-cn/web/api/document/execcommand
```

Somewhere, probably in some KS macro, it attempts to get stuff from disk but it's definitely failing to find something.

**Comment by peterbe** [comment]
As an example, I inject these lines into the top of `read()`
```javascript
  if (!folder.startsWith("en-us/") || folder.includes("/docs/"))
    console.trace(`Unlikely to ever work: '${folder}'`);
```
And the first page I opened was http://localhost:3000/en-US/docs/Games/Techniques/3D_on_the_web which yields this on `stdout`:

```
1:57:07 PM server.1     |  Trace: Unlikely to ever work: 'en-us'
1:57:07 PM server.1     |      at /Users/peterbe/dev/MOZILLA/MDN/yari/content/document.js:151:13
1:57:07 PM server.1     |      at Object.findByURL (/Users/peterbe/dev/MOZILLA/MDN/yari/content/document.js:255:37)
1:57:07 PM server.1     |      at addBreadcrumbData (/Users/peterbe/dev/MOZILLA/MDN/yari/build/document-utils.js:17:32)
1:57:07 PM server.1     |      at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:311:3)
1:57:07 PM server.1     |      at async buildDocumentFromURL (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:323:11)
1:57:07 PM server.1     |      at async /Users/peterbe/dev/MOZILLA/MDN/yari/server/index.js:205:16
1:57:07 PM server.1     |  Trace: Unlikely to ever work: 'en-us'
1:57:07 PM server.1     |      at /Users/peterbe/dev/MOZILLA/MDN/yari/content/document.js:151:13
1:57:07 PM server.1     |      at Object.findByURL (/Users/peterbe/dev/MOZILLA/MDN/yari/content/document.js:255:37)
1:57:07 PM server.1     |      at addBreadcrumbData (/Users/peterbe/dev/MOZILLA/MDN/yari/build/document-utils.js:17:32)
1:57:07 PM server.1     |      at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:311:3)
1:57:07 PM server.1     |      at async buildDocumentFromURL (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:323:11)
1:57:07 PM server.1     |      at async /Users/peterbe/dev/MOZILLA/MDN/yari/server/index.js:205:16
1:57:07 PM server.1     |  buildDocumentFromURL(/en-us/docs/games/techniques/3d_on_the_web): 210.747ms
```

**Comment by peterbe** [comment]
Actually, I noticed that 99.99% of the time this happens is in the flaw detection when it attempts to lookup broken links on hyperlinks. So it's not really a matter (as in, a bug) of the builder or KS. Let's let https://github.com/mdn/yari/pull/1461 close this issue.
