### ISSUE TITLE
Details of PR Build Process Don't Show Where Failure Ocurred

### ISSUE THREAD

**Issue by jpmedley** [mdn/yari#2168]
At the time I'm writing this, PR mdn/content#245 has a failing PR Build process. There appears to be a macro missing a closing bracket, but often these types of failures result from something that's mistyped earlier in the line. This makes it hard enough to find the error. When the information printed on scree doesn't even show where it thinks the error is, we don't have a place to start when looking for it.

![image](https://user-images.githubusercontent.com/8204171/102366919-09e6b880-3f6e-11eb-8b8c-b308da2db5d6.png)

**Comment by peterbe** [comment]
Actually, it does say what line and column it was. This is what I see:

```
~/yari  master ✔
▶ yarn build /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/index.html /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/inherits/index.html /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/initialvalue/index.html /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/name/index.html /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/syntax/index.html
yarn run v1.22.10
$ cross-env NODE_ENV=production node build/cli.js /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/index.html /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/inherits/index.html /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/initialvalue/index.html /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/name/index.html /Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/syntax/index.html

Building SPAs...
Wrote /Users/peterbe/dev/MOZILLA/MDN/yari/client/build/en-us/_spas/404.html

Building Documents...
Building roots: [ '/Users/peterbe/dev/MOZILLA/MDN/content/files' ]
peg$SyntaxError: Expected [ \t\n\r;] or [^(} ] but "(" found.
    at peg$buildStructuredError (/Users/peterbe/dev/MOZILLA/MDN/yari/kumascript/src/parser.js:469:12)
    at Object.peg$parse [as parse] (/Users/peterbe/dev/MOZILLA/MDN/yari/kumascript/src/parser.js:2158:11)
    at Object.getLiveSampleIDs (/Users/peterbe/dev/MOZILLA/MDN/yari/kumascript/src/live-sample.js:122:25)
    at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:200:34)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async buildDocuments (/Users/peterbe/dev/MOZILLA/MDN/yari/build/cli.js:100:9)
    at async Se._action (/Users/peterbe/dev/MOZILLA/MDN/yari/build/cli.js:279:60)
    at async Se.run (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/@caporal/core/dist/index.js:1:27579)
    at async Te._run (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/@caporal/core/dist/index.js:1:32257) {
  expected: [
    {
      type: 'class',
      parts: [Array],
      inverted: false,
      ignoreCase: false
    },
    {
      type: 'class',
      parts: [Array],
      inverted: true,
      ignoreCase: false
    }
  ],
  found: '(',
  location: {
    start: { offset: 1011, line: 22, column: 62 },
    end: { offset: 1012, line: 22, column: 63 }
  }
}

error: Expected [ \t\n\r;] or [^(} ] but "(" found.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Now, supposedly it's on line 22:63. But what file is that?! It's really not obvious.
That's what https://github.com/mdn/yari/issues/2169 is for :)
...which I intend to take a stab at. 
What we'd like to ultimately do is to "rewrite" the error `message` string so it includes the name of the source file and perhaps also the line:column in that too. If possible. Wish me luck! I'm going in.

**Comment by peterbe** [comment]
> But what file is that?! It's really not obvious.

Actually, it's `/Users/peterbe/dev/MOZILLA/MDN/content/files/en-us/web/api/csspropertyrule/index.html` because what `yarn build` does is that it processes them in the order you supply the file names on the CLI and only after it has successfully built does it print what got built. 

Anyway, if you and @rachelandrew want to crack on with https://github.com/mdn/content/pull/245/files that's OK. I have what I need to debug this locally.
