### ISSUE TITLE
IncompleteSignatureException in deployer in prod

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2341]
See https://github.com/mdn/yari/runs/1647132629?check_suite_focus=true

```
...
 Done in 5m1s.
Deployer (0.3.0)
Updating all lambda functions within: aws-lambda
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/work/yari/yari/deployer/src/deployer/main.py", line 60, in update_lambda_functions
    update_all(directory, dry_run=ctx.obj["dry_run"])
  File "/home/runner/work/yari/yari/deployer/src/deployer/update_lambda_functions.py", line 93, in update_all
    info = update(lambda_function_dir, dry_run=dry_run)
  File "/home/runner/work/yari/yari/deployer/src/deployer/update_lambda_functions.py", line 72, in update
    function_info = client.get_function(FunctionName=function_name)
  File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/runner/.cache/pypoetry/virtualenvs/deployer-nuEoiHvI-py3.8/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IncompleteSignatureException) when calling the GetFunction operation: '/20210105/us-east-1/lambda/aws4_request' not a valid key=value pair (missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 Credential=*** /20210105/us-east-1/lambda/aws4_request, SignedHeaders=host;x-amz-date, Signature=f97a2a3e71b3ac7f6064afb2ff1d6bc6b4fe6e7096a46fa4adc010144c5f2523'.
```

Note that the uploading part of the deployer worked. It just failed to upload the lambda function.

**Comment by peterbe** [comment]
@escattone this one. Assign to you?

**Comment by escattone** [comment]
This seems to be a persistent issue, so I'm escalating to P1.

**Comment by escattone** [comment]
This seems to be resolved (see https://github.com/mdn/yari/actions/runs/467311317). Here's what I did:
- (via the the AWS console) invalidated and deleted our existing prod AWS keys (associated with AWS user `mdn-yari-deployer-prod`)
- (via the the AWS console) created new prod AWS keys (associated with AWS user `mdn-yari-deployer-prod`)
- updated the `DEPLOYER_PROD_AWS_ACCESS_KEY_ID` and `DEPLOYER_PROD_AWS_SECRET_ACCESS_KEY` GitHub secrets with the new AWS keys
-  successfully re-ran the `Prod Build` GitHub Action (https://github.com/mdn/yari/actions/runs/467311317)
