### ISSUE TITLE
Fixing flaw from commandline crashes with network timeout

### ISSUE THREAD

**Issue by nschonni** [mdn/yari#2623]
Ran across this running as part of a larger glob of folders, but can reporduce as below with the official `yarn content flaws`

```
$ yarn content flaws Glossary/State_machine
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/tool/cli.js flaws Glossary/State_machine
RequestError: Timeout awaiting 'request' for 10000ms
    at ClientRequest.<anonymous> (Z:\mdn-content\node_modules\got\dist\source\core\index.js:953:65)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (Z:\mdn-content\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Timeout.timeoutHandler [as _onTimeout] (Z:\mdn-content\node_modules\got\dist\source\core\utils\timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1611185586707,
    socket: 1611185586708,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1611185596717,
    abort: undefined,
    phases: {
      wait: 1,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 10010
    }
  },
  event: 'request'
}
RequestError: Timeout awaiting 'request' for 10000ms
    at ClientRequest.<anonymous> (Z:\mdn-content\node_modules\got\dist\source\core\index.js:953:65)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (Z:\mdn-content\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at Timeout.timeoutHandler [as _onTimeout] (Z:\mdn-content\node_modules\got\dist\source\core\utils\timed-out.js:36:25)
    at listOnTimeout (internal/timers.js:556:17)
    at processTimers (internal/timers.js:497:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1611185586707,
    socket: 1611185586708,
    lookup: undefined,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1611185596717,
    abort: undefined,
    phases: {
      wait: 1,
      dns: undefined,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 10010
    }
  },
  event: 'request'
}

error: Timeout awaiting 'request' for 10000ms

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm not sure if `postimg.org` is currently hitting some issues, but I think if it does hit some network issue, it should print a warning instead of a hard crash

**Comment by peterbe** [comment]
I'm OK with it being a "hard crash" as opposed to trying to suppress the problem. 
One thing that would potentially help is to catch the `got` errors, log which URL it was trying to download, and the re-throw. E.g.:
```diff
+try {
   res = await got(url)
+} catch(err) {
+  console.log(`Unable to download image at "${url}"`)
+ throw err
+}
```
that way, you can at least copy and paste the URL from your terminal and try to open it in your browser to see what the hell is going on.

**Comment by nschonni** [comment]
I temporarily monkeypatched the catch in `flaws.js` to
```
      } catch (error) {
        const { response } = error;
        if (response && response.statusCode === 404) {
          console.log(chalk.yellow(`Skipping ${flaw.src} (404)`));
          continue;
        } else {
          console.error(error);
          continue;           // Used to be throw error;
        }
```

**Comment by peterbe** [comment]
I don't like that. :) 
Why would be OK to skip something that should work? I think it's better to be up-front and explicit about it.

**Comment by peterbe** [comment]
Also, why does `got` throw `RequestError: Timeout awaiting 'request' for 10000ms` when the problem was that the URL was 404'ing?!?!

**Comment by nschonni** [comment]
I think the domain itself is dead https://downforeveryoneorjustme.com/postimg.org so there is no server to return a 404.
I would probably wrap/add this error to the first "404" block though rather than falling through though

**Comment by peterbe** [comment]
If the images are dead, it would require manual fixing. 

By the way, I don't see any images on https://developer.mozilla.org/en-US/docs/Glossary/State_machine
Am I blind?

**Comment by nschonni** [comment]
They don't appear because they can't download, but they're in the source `<p><img alt="" src="https://s14.postimg.org/wqu45yc9d/statemachine1.png" loading="lazy"></p>`

**Comment by peterbe** [comment]
Now someone just needs to find a new image to use on `files/en-us/glossary/state_machine/index.html`
Any takers?

**Comment by nschonni** [comment]
I was thinking that WaybackMachine/archive.org would probably be an approach later to see if they could be dug up. Not sure if there might be any licensing issues with scraping them into the repo though.
