### ISSUE TITLE
<img> without a src will crash the flaw checker

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2986]
You get:
```
8:33:09 AM server.1     |  Error in buildDocumentFromURL(/en-us/docs/web/images/srcless) TypeError: Cannot read property 'includes' of undefined
8:33:09 AM server.1     |      at Node.<anonymous> (/Users/peterbe/dev/MOZILLA/MDN/yari/build/check-images.js:314:19)
8:33:09 AM server.1     |      at initialize.exports.each (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/cheerio/lib/api/traversing.js:562:24)
8:33:09 AM server.1     |      at checkImageWidths (/Users/peterbe/dev/MOZILLA/MDN/yari/build/check-images.js:255:12)
8:33:09 AM server.1     |      at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:356:3)
8:33:09 AM server.1     |      at async buildDocumentFromURL (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:500:10)
8:33:09 AM server.1     |      at async /Users/peterbe/dev/MOZILLA/MDN/yari/server/index.js:191:19
```

**Comment by Ryuno-Ki** [comment]
Hm, could a fix check also for missing `alt` attributes?
