### ISSUE TITLE
Unable to download .svg external images because invalid file type

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3072]
Steps to reproduce:
Go to http://localhost:3000/en-US/docs/Web/API/WebXR_Device_API/Fundamentals#_flaws
Press "Fix fixable flaws"

Error:
```
1:48:47 PM server.1     |  Error: No file type could be extracted from https://mdn.mozillademos.org/files/17298/3-degrees-of-freedom-min.svg at all. Probably not going to be a valid image file.
1:48:47 PM server.1     |      at fixFixableFlaws (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:589:17)
1:48:47 PM server.1     |      at runMicrotasks (<anonymous>)
1:48:47 PM server.1     |      at processTicksAndRejections (node:internal/process/task_queues:93:5)
1:48:47 PM server.1     |      at async buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:396:5)
1:48:47 PM server.1     |      at async /Users/peterbe/dev/MOZILLA/MDN/yari/server/document.js:36:5
1:48:47 PM server.1     |  Error: No file type could be extracted from https://mdn.mozillademos.org/files/17298/3-degrees-of-freedom-min.svg at all. Probably not going to be a valid image file.
1:48:47 PM server.1     |      at fixFixableFlaws (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:589:17)
1:48:47 PM server.1     |      at runMicrotasks (<anonymous>)
1:48:47 PM server.1     |      at processTicksAndRejections (node:internal/process/task_queues:93:5)
1:48:47 PM server.1     |      at async buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:396:5)
1:48:47 PM server.1     |      at async /Users/peterbe/dev/MOZILLA/MDN/yari/server/document.js:36:5
1:48:47 PM server.1     |  Error in buildDocument(/en-US/docs/Web/API/WebXR_Device_API/Fundamentals) Error: No file type could be extracted from https://mdn.mozillademos.org/files/17298/3-degrees-of-freedom-min.svg at all. Probably not going to be a valid image file.
1:48:47 PM server.1     |      at fixFixableFlaws (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:589:17)
1:48:47 PM server.1     |      at runMicrotasks (<anonymous>)
1:48:47 PM server.1     |      at processTicksAndRejections (node:internal/process/task_queues:93:5)
1:48:47 PM server.1     |      at async buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:396:5)
1:48:47 PM server.1     |      at async /Users/peterbe/dev/MOZILLA/MDN/yari/server/document.js:36:5
```

What's wrong with https://mdn.mozillademos.org/files/17298/3-degrees-of-freedom-min.svg ??

**Comment by peterbe** [comment]
Curious. It worked perfectly fine with https://mdn.mozillademos.org/files/17125/binocular-vision.svg

The difference is that the `3-degrees-of-freedom-min.svg` image has its preamble stripped. When you download it with `wget` the first couple of bytes are:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 918 918">
```
whereas the `binocular-vision.svg` one is:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0"
```

I'm going to try to see what happens if you "ignore" that and allow it to be downloaded in either form. Will it render fine?

**Comment by peterbe** [comment]
Yeah. Renders fine if you ignore the filetype checking stuff (temporarily). 
I'll make another exception for SVGs.

**Comment by peterbe** [comment]
Fix fixable flaws didn't work on http://localhost:3000/en-US/docs/Web/API/EffectTiming/easing#_flaws

**Comment by peterbe** [comment]
Better wait for https://github.com/mdn/content/pull/2943 because I did the other fixable flaws with that document.

**Comment by peterbe** [comment]
Oops. I fumbled on the button!

**Comment by peterbe** [comment]
The reason the fixable flaws on http://localhost:3000/en-US/docs/Web/API/EffectTiming/easing#_flaws don't work is because the two external images there are 404'ing. It's just too subtle, and that's unfortunate, but it's not a problem with downloading svgs specifically.
