### ISSUE TITLE
Don't crash on <img src="/">

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3190]
If you have `<img src="/">` in the HTML and try to view it through the JIT server with flaw checking this happens:
```
4:09:09 PM server.1     |  Error in buildDocumentFromURL(/en-us/docs/web/images/bad_src) TypeError: Cannot read property 'url' of undefined
4:09:09 PM server.1     |      at Node.<anonymous> (/Users/peterbe/dev/MOZILLA/MDN/yari/build/check-images.js:164:40)
4:09:09 PM server.1     |      at initialize.exports.each (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/cheerio/lib/api/traversing.js:562:24)
4:09:09 PM server.1     |      at checkImageReferences (/Users/peterbe/dev/MOZILLA/MDN/yari/build/check-images.js:70:17)
4:09:09 PM server.1     |      at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:360:27)
4:09:09 PM server.1     |      at async buildDocumentFromURL (/Users/peterbe/dev/MOZILLA/MDN/yari/server/index.js:52:10)
4:09:09 PM server.1     |      at async /Users/peterbe/dev/MOZILLA/MDN/yari/server/index.js:220:19
```

**Comment by peterbe** [comment]
It actually happens with any `<img src>` whose value is an attempt to lookup the "parent document". 
E.g. if the HTML is `<img src="/en-US/xxx">` ends up finding `~/content/mdn/files/en-us` which is a directory. 
The API function `Image.findByURL()` should make sure it only returns things that are images.
