### ISSUE TITLE
Don't choke on iframes without a src

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3271]
Steps to reproduce:
```
BUILD_FLAW_LEVELS="unsafe_html: warn, *:ignore" yarn build /Users/peterbe/dev/MOZILLA/MDN/translated-content/files/es/learn/html/multimedia_and_embedding/responsive_images/index.html
```
You get:
```
Injecting flaws into /Users/peterbe/dev/MOZILLA/MDN/translated-content/files/es/learn/html/multimedia_and_embedding/responsive_images/index.html (/es/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) failed.
TypeError: Cannot read property 'startsWith' of undefined
    at Node.<anonymous> (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:135:17)
    at initialize.exports.each (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/cheerio/lib/api/traversing.js:562:24)
    at injectUnsafeHTMLFlaws (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:129:38)
    at injectFlaws (/Users/peterbe/dev/MOZILLA/MDN/yari/build/flaws.js:58:5)
    at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/yari/build/index.js:368:5)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async buildDocumentInteractive (/Users/peterbe/dev/MOZILLA/MDN/yari/build/cli.js:48:29)
    at async buildDocuments (/Users/peterbe/dev/MOZILLA/MDN/yari/build/cli.js:125:9)
    at async Se._action (/Users/peterbe/dev/MOZILLA/MDN/yari/build/cli.js:300:60)
    at async Se.run (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/@caporal/core/dist/index.js:1:27579)

error: Cannot read property 'startsWith' of undefined
```

**Comment by peterbe** [comment]
I don't even know what the heck this is:
https://github.com/mdn/translated-content/blob/242f0b78b42992e2e1c961fa81172f364d2be6ca/files/es/learn/html/multimedia_and_embedding/responsive_images/index.html#L265
