### ISSUE TITLE
Weird test failures related to puppeteer

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3694]
I started seeing these recently. 
It seems it's flaky, on `main` and the traceback doesn't refer back to anything in our code. 

First I run the contents of `testing/scripts/functional-test.sh` like this:
```
export ENV_FILE=testing/.env

# Temporary whilst only the functional tests use the autocomplete search widget.
export REACT_APP_AUTOCOMPLETE_SEARCH_WIDGET=true

yarn prepare-build
yarn build

yarn test:testing
```
Sometimes it works. Sometimes it fails. I can run `yarn test:testing index` which means jest should avoid anything related to `puppeteer` but it clearly doesn't :(

Here's what an error might look like:

```
 RUNS  tests/redirects.test.js
 RUNS  tests/headless.test.js
 RUNS  tests/developing.test.js
 RUNS  tests/destructive.test.js
 RUNS  tests/sitesearch.test.js
 RUNS  tests/search.test.js
 RUNS  tests/filecheck.test.js
 RUNS  tests/index.test.js

Test Suites: 0 of 8 total
Tests:       0 total
Snapshots:   0 total
Time:        0 s, estimated 4 s
████████████████████████████████████████/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: target should exist before targetInfoChanged
    at Object.assert (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at Browser._targetInfoChanged (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/cjs/puppeteer/common/Browser.js:205:21)
    at /Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at Connection.emit (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at Connection._onMessage (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:115:18)
    at WebSocket.<anonymous> (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:13:32)
    at WebSocket.onMessage (/Users/peterbe/dev/MOZILLA/MDN/yari/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (node:events:329:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by peterbe** [comment]
I tried downgrading to puppeteer 9.0.0 and it seems to make this better. 
The word "target" (in the error) seems very possibly related to https://github.com/puppeteer/puppeteer/pull/7192 which also talks about "target" at lot. 🤷🏻‍♂️
