### ISSUE TITLE
AttributeError inside post_about_dangerous_content() in PR review companion

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3902]
https://github.com/mdn/content/runs/2676360990?check_suite_focus=true

```
 Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/src/deployer/main.py", line 278, in analyze_pr_build
    combined_comment = analyze_pr(directory, ctx.obj)
  File "/home/runner/work/content/content/yari/deployer/src/deployer/analyze_pr.py", line 39, in analyze_pr
    post_about_dangerous_content(build_directory, patch, **config)
  File "/home/runner/work/content/content/yari/deployer/src/deployer/analyze_pr.py", line 136, in post_about_dangerous_content
    href = href.split("#")[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by peterbe** [comment]
Pretty sure it's this PR: https://github.com/mdn/content/pull/5343
I have download the `build.zip` to reproduce and fix.
