### ISSUE TITLE
Markdown converter:  [ERR_REQUIRE_ESM]: Must use import to load ES Modules

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#4607]
Updated my Yari to latest version, ran `yari` to update, and then `yarn md h2m learn/server-side/django --locale en-US`

Now can't convert markdown. Error is:

```
nfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ubuntu@ubuntu:~/github/mdn/yari$ yarn md h2m learn/server-side/django --locale en-US 
yarn run v1.22.10
$ ts-node markdown/cli.ts h2m learn/server-side/django --locale en-US
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/ubuntu/github/mdn/yari/node_modules/rehype-minify-whitespace/index.js
require() of ES modules is not supported.
require() of /home/ubuntu/github/mdn/yari/node_modules/rehype-minify-whitespace/index.js from /home/ubuntu/github/mdn/yari/markdown/h2m/transform.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/ubuntu/github/mdn/yari/node_modules/rehype-minify-whitespace/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ubuntu/github/mdn/yari/markdown/h2m/transform.ts:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/ubuntu/github/mdn/yari/node_modules/ts-node/src/index.ts:1310:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/ubuntu/github/mdn/yari/node_modules/ts-node/src/index.ts:1313:12) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by escattone** [comment]
@hamishwillee Oh man, I'm sorry! This is my fault, but the CI must have passed because we don't actually test the Markdown converter? I'll look into this, thanks for reporting, and again, sorry for this!

**Comment by hamishwillee** [comment]
No worries at all :-). Glad you're on it.

**Comment by escattone** [comment]
@hamishwillee I tried going forward but hit some mysterious Typescript error, so in the end I just reverted (see https://github.com/mdn/yari/pull/4631). This is working again.
