### ISSUE TITLE
Issue: reported a flaw "MacroWrongXRefError from CSSRef" in ja locale

### ISSUE THREAD

**Issue by mfuji09** [mdn/yari#5129]
**MDN URL:** https://developer.mozilla.org/ja/docs/Web/CSS/::first-letter
(and the all articles which uses {{CSSRef}} macro)

When I am using Yari at localhost:5000, the macro {{CSSRef}} produces an error as below every time  in ja or some other locales:

**Macros**
MacroWrongXRefError from CSSRef line 13:1 In prerequisite macro
Explanation: wrong xref macro used (consider changing which macro you use)
Context:
```
   13 | {{CSSRef}}
--------^
   14 | <p><strong><code>::first-letter</code></strong> は <a href="/ja/docs/Web/CSS">CSS</a> の<a href="/ja/docs/Web/CSS/Pseudo-elements">擬似要素</a>で、<a href="/ja/docs/Web/CSS/Visual_formatting_model#block-level_elements_and_block_boxes">ブロックレベル要素</a>の最初の行の最初の文字にスタイルを適用します。ただし、最初の文字より前に他のコンテンツ (画像やインラインテーブルなど) がないときに限ります。</p>
   15 | <pre class="brush: css">/* &#x3C;p> の最初の文字を選択します */
```

Original error stack:
```
Error: wrong xref macro used (consider changing which macro you use)
    at Object.recordNonFatalError (C:\Users\masahiro\Work\MDN\content\node_modules\@mdn\yari\kumascript\src\render.js:115:19)
    at Object.smartLink (C:\Users\masahiro\Work\MDN\content\node_modules\@mdn\yari\kumascript\src\api\web.js:111:27)
    at smartLink ("C:\\Users\\masahiro\\Work\\MDN\\content\\node_modules\\@mdn\\yari\\kumascript\\macros\\CSSRef.ejs":358:14)
    at eval ("C:\\Users\\masahiro\\Work\\MDN\\content\\node_modules\\@mdn\\yari\\kumascript\\macros\\CSSRef.ejs":726:16)
    at async Templates.render (C:\Users\masahiro\Work\MDN\content\node_modules\@mdn\yari\kumascript\src\templates.js:115:22)
    at async render (C:\Users\masahiro\Work\MDN\content\node_modules\@mdn\yari\kumascript\src\render.js:225:32)
    at async Object.renderFromURL [as render] (C:\Users\masahiro\Work\MDN\content\node_modules\@mdn\yari\kumascript\index.js:75:34)
    at async buildDocument (C:\Users\masahiro\Work\MDN\content\node_modules\@mdn\yari\build\index.js:311:29)
    at async buildDocumentFromURL (C:\Users\masahiro\Work\MDN\content\node_modules\@mdn\yari\server\index.js:55:10)
    at async C:\Users\masahiro\Work\MDN\content\node_modules\@mdn\yari\server\index.js:249:19
```

Perhaps the path to "Using_CSS_counters" is incorrect, like as the PR #5090

**Comment by caugner** [comment]
@mfuji09 Sorry it took us so long to get back to you.

Is this still an issue? And if so, could you please share steps to reproduce? Thanks! 🙏
