### ISSUE TITLE
Possible problem with some BCD cells with Chrome 100 and/or Google Translate

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5538]
@schalkneethling Hello. I found another problem that may cause the table to crash.

Use Google Chrome and translate page.

Then quickly click on some elements, there is a certain chance of causing a crash

I recorded a video

https://user-images.githubusercontent.com/16591303/157291103-2d3b3af1-9bf3-4836-abd8-e882b3da9f92.mp4

```txt
react-dom.production.min.js:216 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at wa (https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:184856)
    at Tl (https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:196668)
    at t.unstable_runWithPriority (https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:217284)
    at Uu (https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:139643)
    at Al (https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:194626)
    at vl (https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:190712)
    at https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:139866
    at t.unstable_runWithPriority (https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:217284)
    at Uu (https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:139643)
    at Ku (https://developer.mozilla.org/static/js/4.e6c0e085.chunk.js:2:139811)
aa @ react-dom.production.min.js:216
o.componentDidCatch.n.callback @ react-dom.production.min.js:217
fo @ react-dom.production.min.js:131
ha @ react-dom.production.min.js:220
Tl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uu @ react-dom.production.min.js:122
Al @ react-dom.production.min.js:252
vl @ react-dom.production.min.js:243
（匿名） @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uu @ react-dom.production.min.js:122
Ku @ react-dom.production.min.js:123
Wu @ react-dom.production.min.js:122
je @ react-dom.production.min.js:292
Gt @ react-dom.production.min.js:73
```

_Originally posted by @liyuhang1997 in https://github.com/mdn/yari/issues/5520#issuecomment-1062006143_

**Comment by schalkneethling** [comment]
@liyuhang1997 I did a quick test using Chrome Canary(v101) and could not reproduce. So, you said that this is using the page with Google Translate, correct? Into which language are you translating? I switched to Chinese using our language switcher and everything still worked fine.

**Comment by liyuhang1997** [comment]
Regardless of translation into any language.

I've found that crashes often occur when switching between "No Support" checkmarks and other checkmarks on the same line.

**Comment by schalkneethling** [comment]
Than you for the additional information @liyuhang1997
