### ISSUE TITLE
The CI failed when I fetch content repo

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/yari#6739]
`PR review companion workflow run failed for main branch`

The stack trace:
```
Run PR_NUMBER=`cat build/NR`
Pull request:
https://github.com/mdn/content/pull/
Deployer (0.3.0)
Upload files from: /home/runner/work/content/content/build
Upload into: pr/ of mdn-content-dev
Total pending file uploads: 1,072 ([39](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:40).9ms)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 1[40](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:41)4, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/src/deployer/main.py", line 200, in upload
    upload_content(directory, content_roots, ctx.obj)
  File "/home/runner/work/content/content/yari/deployer/src/deployer/upload.py", line 549, in upload_content
    existing_bucket_objects = mgr.get_bucket_objects()
  File "/home/runner/work/content/content/yari/deployer/src/deployer/upload.py", line 352, in get_bucket_objects
    response = self.client.list_objects_v2(**kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/client.py", line 898, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/client.py", line 921, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/hooks.py", line [41](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:42)2, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 2[56](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:57), in emit
    return self._emit(event_name, kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/signers.py", line 103, in handler
    return self.sign(operation_name, request)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/signers.py", line 1[87](https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:88), in sign
    auth.add_auth(request)
  File "/home/runner/work/content/content/yari/deployer/.venv/lib/python3.8/site-packages/botocore/auth.py", line 407, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
Total existing S3 objects: 
Error: Process completed with exit code 1.
```

**Comment by awxiaoxian2020** [comment]
> [AWS S3 credentials](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html) are required for this workflow
> 
> ![image](https://user-images.githubusercontent.com/15844309/179430408-490a3f83-256a-4b81-9695-ff6528f5a72d.png)

Where I can find the file you post in the picture and Can I do something about it?

**Comment by yin1999** [comment]
see: <https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:34>. You need to configure aws S3, CloudFront, and Lambda@Edge for running workflow in your forked repo. It's not a easy job, and it's better to not enable actions in forked repo.

**Comment by awxiaoxian2020** [comment]
> see: https://github.com/awxiaoxian2020/content/runs/7369518508?check_suite_focus=true#step:11:34. You need to configure aws S3, CloudFront, and Lambda@Edge for running workflow in your forked repo. It's not a easy job, and it's better to not enable actions in forked repo.

How can I disable the workflow in my fork repo? As far as I know, It can configure in the mdn repo. Although I'm not familiar with github workflows.

**Comment by cw118** [comment]
> How can I disable the workflow in my fork repo? As far as I know, It can configure in the mdn repo. Although I'm not familiar with github workflows.

You should be able to disable a workflow manually in the "Actions" tab of your fork by clicking on the "PR review companion" workflow, then clicking the three dot menu:

![disable-workflow](https://user-images.githubusercontent.com/87150472/164938751-d529388d-e113-474e-80f4-5a5b903a095f.png)

**Comment by awxiaoxian2020** [comment]
> > How can I disable the workflow in my fork repo? As far as I know, It can configure in the mdn repo. Although I'm not familiar with github workflows.
> 
> You should be able to disable a workflow manually in the "Actions" tab of your fork by clicking on the "PR review companion" workflow, then clicking the three dot menu:
> 
> ![disable-workflow](https://user-images.githubusercontent.com/87150472/164938751-d529388d-e113-474e-80f4-5a5b903a095f.png)

Thank you very much indeed! And I want to know it is necessary that this workflow exists in some fork repos? If not, I think we should modify the yml file to make it only in original repo.
After all, I only receive the workflow in `content` repo, not in `yari` or `translated-content`.

**Comment by awxiaoxian2020** [comment]
I'm very sorry to reopen this issue. I re-fork the translation-content repo for some reasons and I haven't found the Disable workflow now.
![issue](https://user-images.githubusercontent.com/69554233/185771096-35b895ec-9edc-4578-8e27-817fad2b9bca.png)

**Comment by yin1999** [comment]
You can disable all the workflow in repo's settings.

**Comment by awxiaoxian2020** [comment]
Now my problem is duplicated in #4972
