### ISSUE TITLE
watcher breaks when you add new content or change slug

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#677]
Steps to reproduce:

1. `yarn clean && yarn start`
2. Create a new folder in `content/files/en-us/something`
3. Create a new `index.html` file there
4. Edit it once

```
5:09:54 PM watchcontent.1 |  change in /Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/somethingnew
5:09:54 PM watchcontent.1 |  (node:16015) UnhandledPromiseRejectionWarning: Error: /en-us/docs/glossary/png3 is not present in this.allTitles
5:09:54 PM watchcontent.1 |      at Builder.processFolder (/Users/peterbe/dev/MOZILLA/MDN/yari/content/scripts/build.js:1642:13)
5:09:54 PM watchcontent.1 |      at processTicksAndRejections (internal/process/task_queues.js:97:5)
5:09:54 PM watchcontent.1 |      at async onChange (/Users/peterbe/dev/MOZILLA/MDN/yari/content/scripts/build.js:872:37)
5:09:54 PM watchcontent.1 |  (node:16015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
5:09:54 PM watchcontent.1 |  (node:16015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Another thing you can do is to open any existing `index.html` and change the slug. 
Granted, you shouldn't be doing this anyway because editing a slug, manually, without adding the old slug to `_redirects.txt` is going to be a problem.

**Comment by peterbe** [comment]
Assigning to myself since I already have a solution inside https://github.com/Gregoor/stumptown-renderer/pull/1
