### ISSUE TITLE
Flaky test: testing/tests/developing.spec.ts:31:3 › Testing the kitchensink page › open the page

### ISSUE THREAD

**Issue by caugner** [mdn/yari#6960]
```
  1) testing/tests/developing.spec.ts:31:3 › Testing the kitchensink page › open the page ==========

    Error: expect(received).toBeTruthy()

    Received: false

      41 |     expect(
      42 |       await page.isVisible("text=No known flaws at the moment")
    > 43 |     ).toBeTruthy();
         |       ^
      44 |   });
      45 |
      46 |   test("open a file attachement directly in the dev URL", async ({ page }) => {

        at /home/runner/work/yari/yari/testing/tests/developing.spec.ts:43:7
```

Source: https://github.com/mdn/yari/runs/8019448842?check_suite_focus=true#step:10:11

**Comment by caugner** [comment]
Again: https://github.com/mdn/yari/runs/8023570697?check_suite_focus=true

**Comment by caugner** [comment]
Here's another flaky test:

```
   1) testing/tests/headless.sitesearch.spec.ts:59:3 › Site search › search and go to page 2 ========

    Error: expect(received).toBeTruthy()

    Received: false

      79 |     await page.click('a:has-text("Next")');
      80 |     expect(await page.isVisible("text=(page 2)")).toBeTruthy();
    > 81 |     expect(await page.isVisible("text=Serial 10")).toBeTruthy();
         |                                                    ^
      82 |     expect(await page.isVisible("text=Serial 19")).toBeTruthy();
      83 |     expect(await page.isVisible('a:has-text("Previous")')).toBeTruthy();
      84 |     expect(await page.isVisible('a:has-text("Next")')).toBeFalsy();

        at /home/runner/work/yari/yari/testing/tests/headless.sitesearch.spec.ts:81:52
```

Source: https://github.com/mdn/yari/runs/8023892333?check_suite_focus=true#step:10:26

**Comment by caugner** [comment]
Again: https://github.com/mdn/yari/runs/8070722001?check_suite_focus=true#step:10:11
