### ISSUE TITLE
Clean quickstart environment doesn't work

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#781]
If you follow the instructions here: https://github.com/mdn/yari#quickstart
And then go to http://localhost:3000/en-US/docs/Web/HTML/Element/audio you get this error:

```
3:20:04 PM web.1          |  You can now view client in the browser.
3:20:04 PM web.1          |    Local:            http://localhost:3000
3:20:04 PM web.1          |    On Your Network:  http://192.168.1.209:3000
3:20:04 PM web.1          |  Note that the development build is not optimized.
3:20:04 PM web.1          |  To create a production build, use npm run build.
3:20:15 PM server.1       |  Building a map of ALL redirects...
3:20:15 PM server.1       |  Building map of all redirects took 0 ms
3:20:15 PM server.1       |  Error: Unable to find the source based on /private/tmp/yari/content/files/en-us/web/html/element/audio
3:20:15 PM server.1       |      at Builder.getSource (/private/tmp/yari/content/scripts/build.js:496:13)
3:20:15 PM server.1       |      at Builder.start (/private/tmp/yari/content/scripts/build.js:593:23)
3:20:15 PM server.1       |      at /private/tmp/yari/server/index.js:624:50
3:20:15 PM server.1       |      at Layer.handle [as handle_request] (/private/tmp/yari/node_modules/express/lib/router/layer.js:95:5)
3:20:15 PM server.1       |      at next (/private/tmp/yari/node_modules/express/lib/router/route.js:137:13)
3:20:15 PM server.1       |      at Route.dispatch (/private/tmp/yari/node_modules/express/lib/router/route.js:112:3)
3:20:15 PM server.1       |      at Layer.handle [as handle_request] (/private/tmp/yari/node_modules/express/lib/router/layer.js:95:5)
3:20:15 PM server.1       |      at /private/tmp/yari/node_modules/express/lib/router/index.js:281:22
3:20:15 PM server.1       |      at param (/private/tmp/yari/node_modules/express/lib/router/index.js:354:14)
3:20:15 PM server.1       |      at param (/private/tmp/yari/node_modules/express/lib/router/index.js:365:14)
```

**Comment by peterbe** [comment]
The problem seems to be that `this.sources.entries()` becomes an empty list. 
Most likely due to no `.env` file being present so it doesn't use the defaults.

**Comment by peterbe** [comment]
Ah! The server does this:
```
function getOrCreateBuilder(options) {
  options = options || {};
  if (!builder) {
    const sources = new Sources();
    // The server doesn't have command line arguments like the content CLI
    // does so we need to entirely rely on environment variables.
    if (process.env.BUILD_ROOT) {
      sources.add(normalizeContentPath(process.env.BUILD_ROOT));
    }
```
Unlike the build CLI (content/index.js) which relies on a default from constants.
