### ISSUE TITLE
Running Yarn build without ever running yarn dev will result in error 

### ISSUE THREAD

**Issue by tlylt** [mdn/yari#8135]
### Summary

I just cloned the repository following the guide in the README.

After this step [`copy the .env-dist file to .env`](https://github.com/mdn/yari#:~:text=Now%20copy%20the%20.env%2Ddist%20file%20to%20.env%3A) it was said that:
> At this point, you can get started.

I did not run `yarn dev` and instead ran `yarn build` for the first time ever, which resulted in the following error:
> $ yarn build
yarn run v1.22.5
warning ..\..\..\package.json: No license field
$ cross-env NODE_ENV=production ts-node build/cli.ts
Error: Cannot find module '../ssr/dist/main'
> Require stack:
> - C:\Users\User\Documents\GitHub\yari\build\cli.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Users\User\Documents\GitHub\yari\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\User\Documents\GitHub\yari\build\cli.ts:17:15)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module.m._compile (C:\Users\User\Documents\GitHub\yari\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\User\Documents\GitHub\yari\node_modules\ts-node\src\index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Users\\User\\Documents\\GitHub\\yari\\build\\cli.ts' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The error disappeared after I have done `yarn dev`.

I think adding a note in the README to mention that you need to run `yarn dev` once before you can run `yarn build` would be helpful.

### URL

nil

### Reproduction steps

1. Follow the Quickstart guide in README, stop after copying the env
2. Run `yarn build`

### Expected behavior

no error

### Actual behavior

error

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by tlylt** [comment]
> Please run `yarn build:prepare` first. This command would do some preparing jobs.

I see, is this mentioned anywhere? Would be good to communicate this info to new developers.

**Comment by caugner** [comment]
Thank you for taking the time to open this issue. 👍 

I had a look and the README states:

> At this point, you can get started. **Run the following lines to compile required files**, start the Yari web server running, and open it in your browser:

So I wouldn't say that this suggests that you can run a command like `yarn build` without running `yarn dev` before, so I will go ahead and close this issue as "won't fix".

PS: If you checkout [mdn/content](https://github.com/mdn/content) though, you can run `yarn build` immediately after running `yarn install`.
