### ISSUE TITLE
Local build of content no longer works on Windows using yarn start

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#8201]
### Summary

Windows 11, I synced to mdn/content main, which required me to update node to 18+. I then did a `yarn install`. This crashes, so I can no longer test locally:

```
D:\github\mozilla\content>yarn install
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@mdn/yari > @use-it/interval@1.0.0" has unmet peer dependency "react@>=16.8".
warning "@mdn/yari > html-react-parser@3.0.8" has unmet peer dependency "react@0.14 || 15 || 16 || 17 || 18".
warning "@mdn/yari > react-modal@3.16.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16 || ^17 || ^18".
warning "@mdn/yari > react-modal@3.16.1" has unmet peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16 || ^17 || ^18".
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 2.08s.

D:\github\mozilla\content>yarn start
yarn run v1.22.5
$ yarn up-to-date-check && env-cmd --silent cross-env CONTENT_ROOT=files REACT_APP_DISABLE_AUTH=true BUILD_OUT_ROOT=build yari-server
$ node scripts/up-to-date-check.js
(node:62904) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66688) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute
    at new NodeError (node:internal/errors:399:5)
    at getPathFromURLWin32 (node:internal/url:1463:11)
    at fileURLToPath (node:internal/url:1493:22)
    at file:///D:/github/mozilla/content/node_modules/@mdn/yari/ssr/dist/main.js:2:791999
    at file:///D:/github/mozilla/content/node_modules/@mdn/yari/ssr/dist/main.js:2:797344
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'ERR_INVALID_FILE_URL_PATH'
}

Node.js v18.14.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### URL

NA 

### Reproduction steps

As above:
- Get mdn/content , main branch, latest
- Node up to some 18 version
- `yarn install`
- `yarn start`

Crashes

### Expected behavior

The local server runs and I can look at pages

### Actual behavior

Build crashes

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by yin1999** [comment]
Related to #8177. I'm not sure would this be a solution: https://github.com/webpack/webpack/issues/14072#issuecomment-1175944354

**Comment by SphinxKnight** [comment]
@caugner
`yarn add @mdn/yari@2.1.6-rc3 && yarn start ` fixed it on my `mdn/content` local repo.

However, on the yari side, I tried https://github.com/mdn/yari/tree/fix-start-on-windows on my windows 10 machine and still get a build error 

```
yarn run v1.22.19
$ (test -f client/build/index.html || yarn build:client) && (test -f ssr/dist/main.js || yarn build:ssr) && (test -d client/build/en-us/_spas || yarn tool spas) && nf -j Procfile.start start
[OKAY] Loaded ENV .env File as KEY=VALUE Format
13:11:10 server.1   |  $ ts-node server/index.ts
13:11:10 web.1      |  $ cd client && cross-env NODE_ENV=development BABEL_ENV=development BROWSER=none PORT=3000 node scripts/start.js
13:11:15 server.1   |  (node:4768) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
13:11:15 server.1   |  (Use `node --trace-warnings ...` to show where the warning was created)
13:11:19 server.1   |  file:///C:/Users/jg/mdn/yari/build/spas.ts:14
13:11:19 server.1   |  import { renderHTML } from "../ssr/dist/main.js";
13:11:19 server.1   |           ^^^^^^^^^^
13:11:19 server.1   |  SyntaxError: The requested module '../ssr/dist/main.js' does not provide an export named 'renderHTML'
13:11:19 server.1   |      at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
13:11:19 server.1   |      at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
13:11:19 server.1   |  error Command failed with exit code 1.
13:11:19 server.1   |  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

At first glance, I'd say #8219 does not fully fix the issue.

**Comment by hamishwillee** [comment]
Yes it is. Thanks for getting this in - makes my life a lot easier.
