### ISSUE TITLE
Figure out how to display SVGs as React components

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#882]
In `create-react-app` the way to display a `.svg` is like this:
https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs

That still works in Yari's front-end but it breaks in SSR. You get:
```
4:29:05 PM server.1    |  Error: Minified React error #65; visit https://reactjs.org/docs/error-decoder.html?invariant=65&args[]=%2Fdistimages%2F15e6bc84d57259b924f26fbc6bedccca.svg for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
4:29:05 PM server.1    |      at e.t.renderDOM (/Users/peterbe/dev/MOZILLA/MDN/yari/ssr/dist/main.js:22:16599)
4:29:05 PM server.1    |      at e.t.render (/Users/peterbe/dev/MOZILLA/MDN/yari/ssr/dist/main.js:22:15013)
4:29:05 PM server.1    |      at e.t.read (/Users/peterbe/dev/MOZILLA/MDN/yari/ssr/dist/main.js:22:14239)
4:29:05 PM server.1    |      at renderToString (/Users/peterbe/dev/MOZILLA/MDN/yari/ssr/dist/main.js:22:19845)
4:29:05 PM server.1    |      at Z.i.a.createElement.location (/Users/peterbe/dev/MOZILLA/MDN/yari/ssr/dist/main.js:22:37343)
4:29:05 PM server.1    |      at Z (/Users/peterbe/dev/MOZILLA/MDN/yari/ssr/dist/main.js:22:37713)
4:29:05 PM server.1    |      at Builder.processFolder (/Users/peterbe/dev/MOZILLA/MDN/yari/content/scripts/build.js:1800:42)
4:29:05 PM server.1    |      at async Builder.start (/Users/peterbe/dev/MOZILLA/MDN/yari/content/scripts/build.js:533:23)
4:29:05 PM server.1    |      at async /Users/peterbe/dev/MOZILLA/MDN/yari/server/index.js:516:23
```

The temporary workaround is to do:
```diff
-import { ReactComponent as Logo } from './logo.svg';
+import Logo from './logo.svg';

function App() {
  return (
    <div>
-     {/* Logo is an actual React component */}
-     <Logo />
-     <img src={Logo} alt="Logo"/>
    </div>
  );
}
```
But that's obviously different. Because you get a `<img>` tag vs a `<svg>` tag.

**Comment by peterbe** [comment]
Actually, https://github.com/mdn/yari/pull/884 solves this just fine.
